name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Repository
      - name: Downloading repo
        uses: actions/checkout@v3
      # Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      # Selenoid
      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2
      # Launch tests
      - name: Gradlew run test
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub
      # Allure report
      - name: tests history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Making report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Publishing report
        uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history